### ISSUE TITLE
Automated tests are failing due to bootstrap_layouts module

### ISSUE THREAD

**Issue by CraigClark** [bcgov/bcbb#14]
**OP timer**

---

## Describe the bug

We found an issue with a contributed module that is causing automated tests to fail. The issue [was reported to the maintainer](https://www.drupal.org/project/bootstrap_layouts/issues/3367366)

This needs to be discussed at a base-build meeting.

The [bootstrap_layouts module](https://www.drupal.org/project/bootstrap_layouts) is used by page manager to provide the layout we are using for the search result page. This module is convenient because it has multiple BS5 layouts to choose from. You can also add custom classes to regions.

Making custom layouts is not a bug deal, it would get around the issue we have with tests failing. The down side of custom layouts is that they are typically done in code. So the options provided by bootstrap_layouts would not be available to site builders. 

That being said, the inability to write automated tests is a serious issue, especially for a feature as important as search.

## Task

As a team, figure out if we want to stay with bootstrap_layouts. If now, what do we do instead?

Related: 

- https://github.com/bcgov/MFIN-Data-Catalogue/wiki/Test-plan
- https://github.com/bcgov/bcbb/issues/13

**Comment by CraigClark** [comment]
This was discussed at the base-build meeting today. 

**Actions**

- [ ] OP to discuss internally what the issue is with core layout builder module and report back to Nicole tomorrow.

*Choose one of*

- [ ] Layout builder is suitable > rebuild search page with layout builder
- [ ]  layout builder is not suitable > make custom display mode for page manager. Meet with BB team to show how it works in code.
